# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48b86377eace41029b0c7f522f51723137d17132d1c718ee4688512921f52747479e5f9d12eb851a354d256ffbbe5a5fe8706c9432f0d8069cc45ec4acf80ef2

test:
  secret_key_base: 314ca1fc24cb8cd97ae8ab9d056aede20060c7fdcb47a9ea6167adeb13ace22e18360f735f080e9e32c66737a8fde97f5a35f403c4d323bf3d33b6800eceede8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
